export const defaultEmployees = [
  {
    id: 1,
    firstName: 'Tristan',
    lastName: 'Robertson',
    department: 'Finance',
    position: 'Junior',
    email: 'tristan.robertson@example.com',
    phone: '234-567-9012',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 2,
    firstName: 'Ursula',
    lastName: 'Morris',
    department: 'Marketing',
    position: 'Junior',
    email: 'ursula.morris@example.com',
    phone: '345-678-0123',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 3,
    firstName: 'Victor',
    lastName: 'Long',
    department: 'Customer Service',
    position: 'Junior',
    email: 'victor.long@example.com',
    phone: '456-789-1234',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 4,
    firstName: 'Willa',
    lastName: 'Hernandez',
    department: 'Engineering',
    position: 'Junior',
    email: 'willa.hernandez@example.com',
    phone: '567-890-2345',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 5,
    firstName: 'Xena',
    lastName: 'James',
    department: 'Development',
    position: 'Junior',
    email: 'xena.james@example.com',
    phone: '678-901-3456',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 6,
    firstName: 'Yusuf',
    lastName: 'Nelson',
    department: 'Research',
    position: 'Junior',
    email: 'yusuf.nelson@example.com',
    phone: '789-012-4567',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 7,
    firstName: 'Zara',
    lastName: 'Meyer',
    department: 'Sales',
    position: 'Junior',
    email: 'zara.meyer@example.com',
    phone: '890-123-5678',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 8,
    firstName: 'Adrian',
    lastName: 'Gonzalez',
    department: 'Logistics',
    position: 'Junior',
    email: 'adrian.gonzalez@example.com',
    phone: '901-234-6789',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 9,
    firstName: 'Bella',
    lastName: 'Perry',
    department: 'HR',
    position: 'Medior',
    email: 'bella.perry@example.com',
    phone: '012-345-7890',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 10,
    firstName: 'Cameron',
    lastName: 'Butler',
    department: 'Analytics',
    position: 'Junior',
    email: 'cameron.butler@example.com',
    phone: '123-456-8901',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 11,
    firstName: 'Diana',
    lastName: 'Bennett',
    department: 'IT',
    position: 'Junior',
    email: 'diana.bennett@example.com',
    phone: '234-567-9012',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 12,
    firstName: 'Ethan',
    lastName: 'Coleman',
    department: 'Development',
    position: 'Junior',
    email: 'ethan.coleman@example.com',
    phone: '345-678-0123',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 13,
    firstName: 'Fiona',
    lastName: 'Floyd',
    department: 'Research',
    position: 'Junior',
    email: 'fiona.floyd@example.com',
    phone: '456-789-1234',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 14,
    firstName: 'Grayson',
    lastName: 'Parker',
    department: 'Sales',
    position: 'Junior',
    email: 'grayson.parker@example.com',
    phone: '567-890-2345',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 15,
    firstName: 'Liam',
    lastName: 'Smithson',
    department: 'Research',
    position: 'Junior',
    email: 'liam.smithson@example.com',
    phone: '321-654-9870',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 16,
    firstName: 'Mia',
    lastName: 'Williams',
    department: 'Logistics',
    position: 'Junior',
    email: 'mia.williams@example.com',
    phone: '654-789-1234',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 17,
    firstName: 'Noah',
    lastName: 'Wilson',
    department: 'Management',
    position: 'Medior',
    email: 'noah.wilson@example.com',
    phone: '987-321-5640',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 18,
    firstName: 'Olivia',
    lastName: 'Martinez',
    department: 'Customer Service',
    position: 'Junior',
    email: 'olivia.martinez@example.com',
    phone: '654-123-7890',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 19,
    firstName: 'Paul',
    lastName: 'Hernandez',
    department: 'Legal',
    position: 'Junior',
    email: 'paul.hernandez@example.com',
    phone: '890-123-4567',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 20,
    firstName: 'Quinn',
    lastName: 'Lopez',
    department: 'IT',
    position: 'Junior',
    email: 'quinn.lopez@example.com',
    phone: '234-567-8901',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 21,
    firstName: 'Rita',
    lastName: 'Clark',
    department: 'Development',
    position: 'Junior',
    email: 'rita.clark@example.com',
    phone: '345-678-9012',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 22,
    firstName: 'Steve',
    lastName: 'Lewis',
    department: 'Production',
    position: 'Senior',
    email: 'steve.lewis@example.com',
    phone: '987-654-3210',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 23,
    firstName: 'Tina',
    lastName: 'Walker',
    department: 'Procurement',
    position: 'Junior',
    email: 'tina.walker@example.com',
    phone: '123-456-7890',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 24,
    firstName: 'Ulysses',
    lastName: 'Hall',
    department: 'Training',
    position: 'Junior',
    email: 'ulysses.hall@example.com',
    phone: '678-901-2345',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 25,
    firstName: 'Vera',
    lastName: 'King',
    department: 'Quality Assurance',
    position: 'Medior',
    email: 'vera.king@example.com',
    phone: '234-567-8901',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 26,
    firstName: 'Walter',
    lastName: 'Young',
    department: 'Analytics',
    position: 'Junior',
    email: 'walter.young@example.com',
    phone: '345-678-9012',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 27,
    firstName: 'Xena',
    lastName: 'Thompson',
    department: 'HR',
    position: 'Junior',
    email: 'xena.thompson@example.com',
    phone: '654-321-0987',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 28,
    firstName: 'Yves',
    lastName: 'White',
    department: 'Sales',
    position: 'Junior',
    email: 'yves.white@example.com',
    phone: '987-654-3210',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 29,
    firstName: 'Zara',
    lastName: 'Harris',
    department: 'Development',
    position: 'Junior',
    email: 'zara.harris@example.com',
    phone: '123-456-7890',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 30,
    firstName: 'Alvin',
    lastName: 'Gray',
    department: 'R&D',
    position: 'Senior',
    email: 'alvin.gray@example.com',
    phone: '321-654-9870',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 31,
    firstName: 'Bella',
    lastName: 'Perry',
    department: 'HR',
    position: 'Medior',
    email: 'alvin.gray@example.com',
    phone: '321-654-9870',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 32,
    firstName: 'Clla',
    lastName: 'Qerry',
    department: 'HR',
    position: 'Junior',
    email: 'clla.qerry@example.com',
    phone: '321-654-9870',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
  {
    id: 33,
    firstName: 'Dlla',
    lastName: 'Serry',
    department: 'HR',
    position: 'Senior',
    email: 'dlla.serry@example.com',
    phone: '321-654-9870',
    employmentDate: '11/11/2022',
    dateOfBirth: '10/10/2000',
  },
];

function loadEmployeesFromStorage() {
  const storedEmployees = JSON.parse(localStorage.getItem('employees'));
  if (!storedEmployees) {
    saveEmployeesToStorage(defaultEmployees);
    return defaultEmployees;
  }
  return storedEmployees;
}

function saveEmployeesToStorage(employees) {
  localStorage.setItem('employees', JSON.stringify(employees));
}

export function getEmployees() {
  return loadEmployeesFromStorage();
}

export function addEmployee(employee) {
  const employees = loadEmployeesFromStorage();
  employees.push({...employee, id: Date.now()});
  saveEmployeesToStorage(employees);
}

export function deleteEmployee(id) {
  const employees = loadEmployeesFromStorage();
  const updatedEmployees = employees.filter((employee) => employee.id !== id);
  saveEmployeesToStorage(updatedEmployees);
}

export function updateEmployee(updatedEmployee) {
  const employees = loadEmployeesFromStorage();
  const index = employees.findIndex(
    (employee) => employee.id === updatedEmployee.id
  );
  if (index !== -1) {
    employees[index] = updatedEmployee;
    saveEmployeesToStorage(employees);
  }
}
